# This is an updated config for using I3D on 360+x, resulting in slightly
# better performance. Setting batch_size smaller to get better performance.

dataset_name: x360_temporal
train_split: ['train']
val_split: ['val']

dataset: {
  panoramic_feat_file: "video_feat.npy",
  front_view_feat_file: "video_feat.npy",
  binocular_feat_file: "video_feat.npy",

  file_prefix: ~,
  file_ext: .npy,
  num_classes: 29,
  input_dim: 2048,
  feat_stride: 1,
  num_frames: 16,
  default_fps: 25,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}


model: {
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  backbone_arch: [ 2, 2, 5 ],
  n_sgp_win_size: 15,
  regression_range: [ [ 0, 4 ], [ 4, 8 ], [ 8, 16 ], [ 16, 32 ], [ 32, 64 ], [ 64, 10000 ] ],
  embd_dim: 256,
  sgp_mlp_dim: 2048,
  fpn_dim: 256,
  head_dim: 512,
  use_abs_pe: True,
  num_bins: 12,
  iou_weight_power: 1,
  input_noise: 0.5,
  k: 1.3,
  init_conv_vars: 0.2,
}

opt: {
  learning_rate: 0.0001,
  epochs: 500,
  weight_decay: 0.0005,  # 0.05
  eta_min: 0.00005,
  warmup_epochs: 10,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 400,
  clip_grad_l2norm: 0.4,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
  loss_weight: 2.0,
}

test_cfg: {
  voting_thresh: 0.5,   # 0.5
  nms_sigma: 3.0,       #
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  multiclass_nms: True,
  iou_threshold: 0.01,      # 0.1 merge iou
  duration_thresh: 0.001,
  post_thr: 0.1
}
output_folder: ./ckpt




