# This is an updated config for using I3D on 360+x, resulting in slightly
# better performance. Setting batch_size smaller to get better performance.

dataset_name: x360_temporal
train_split: ['train']
val_split: ['val']
dataset: {
  panoramic_feat_file: "video_feat.npy",
  front_view_feat_file: "video_feat.npy",
  binocular_feat_file: "video_feat.npy",

  file_prefix: ~,
  file_ext: .npy,
  num_classes: 29,
  input_dim: 2048,
  feat_stride: 1,
  num_frames: 16,
  default_fps: 25,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  # 192 - 96 - 48 - 24 - 12 - 6
  n_mha_win_size: [7, 7, 7, 7, 7, -1],
  n_head: 4,
  embd_dim: 256,
  fpn_dim: 256,
  head_dim: 256,
  use_abs_pe: True,
}
opt: {
  learning_rate: 0.0001,
  epochs: 500,
  weight_decay: 0.0005,  # 0.05
  eta_min: 0.00005,
  warmup_epochs: 10,
}
loader: {
  batch_size: 4, #8
}
train_cfg: {
  init_loss_norm: 200,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
  droppath: 0.1,
  loss_weight: 2.0,
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.5,
  pre_nms_topk: 2000,
  max_seg_num: 100,
  min_score: 0.001,
  multiclass_nms: True,
  nms_sigma: 0.8,  # 0.6
#  iou_threshold: 0.5, # 0.5
  duration_thresh: 0.001,
  post_thr: 0.7
}
output_folder: ./ckpt


