# This is an updated config for using I3D on 360+x, resulting in slightly
# better performance. Setting batch_size smaller to get better performance.

model_name: "TemporalMaxerArchitecture"
dataset_name: x360_temporal
train_split: ['train']
val_split: ['val']

dataset: {
  panoramic_feat_file: "video_feat.npy",
  front_view_feat_file: "video_feat.npy",
  binocular_feat_file: "video_feat.npy",

  file_prefix: ~,
  file_ext: .npy,
  num_classes: 29,
  input_dim: 2048,
  feat_stride: 1,
  num_frames: 16,
  default_fps: 25,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}
model: {
  backbone_type: convPooler,
  backbone_arch: [2, 5],      # [#feature projection layers, #downsampling layer]
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  assigner: {
    iou_weight: 2,
    cls_weight: 1.0,
    center_radius: 1.5,
    keep_percent: 1.0,
    confuse_weight: 0.0
  }
}
opt: {
  learning_rate: 0.0001,
  epochs: 500,
  weight_decay: 0.0005,  # 0.05
  eta_min: 0.00005,
  warmup_epochs: 10,
}

loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: 'none',
}
test_cfg: {
  voting_thresh: 0.5,
  nms_sigma: 0.7,    # 0.375
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  iou_threshold: 0.01, # 0.5
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
  post_thr: 0.8
}
output_folder: ./ckpt

